package:
  name: raygun4py
  version: "3.0.3"

source:
  fn: raygun4py-3.0.3.tar.gz
  url: https://github.com/MindscapeHQ/raygun4py/archive/v3.0.3.tar.gz
 
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - raygun4py = raygun4py:main
    #
    # Would create an entry point called raygun4py that calls raygun4py.main()

    - raygun4py = raygun4py.cli:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - jsonpickle ==0.9.2
    - blinker ==1.3.0
    - requests ==2.9.1

  run:
    - python
    - jsonpickle ==0.9.2
    - blinker ==1.3.0
    - requests ==2.9.1

test:
  # Python imports
  imports:
    - raygun4py

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - raygun4py --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://raygun.io
  license: MIT License
  summary: 'Official Raygun provider for Python 2.6/2.7 and Python 3+'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
